### ISSUE TITLE
A missing semicolon at the last line removes the whole line

### ISSUE THREAD

**Issue by chocolateimage** [chocolateimage/chocotools#1]
If you have a CSS file like this:
```css
.element {
    width: 100%;
    height: 100%
}
```

The last line without a semicolon will get completely removed.

It should either:
1. Stay the way without semicolon
2. Add the missing semicolon
