### ISSUE TITLE
Semicolons are automatically being placed at the end of comments.

### ISSUE THREAD

**Issue by chocolateimage** [chocolateimage/chocotools#3]
When writing a comment at the end of a property like this:

```css
element {
    display: flex;

    color: white; /* Example comment */
}
```

A semicolon is being added at the end of the comment making it look weird:
```css
    color: white; /* Example comment */;
```
