### ISSUE TITLE
Unfinished comment causes entire file to glitch out

### ISSUE THREAD

**Issue by chocolateimage** [chocolateimage/chocotools#4]
I don't have much time to write this issue but this causes everything to glitch out, especially when Prettier is enabled:
```css
element1 {
    color: white;
    /*
    background: black;
}

element2 {
    padding: 4px;
}
```
