### ISSUE TITLE
[CSS orderer] Comments get duplicated

### ISSUE THREAD

**Issue by chocolateimage** [chocolateimage/chocotools#5]
Adding a comment can sometimes get duplicated when formatted

Original:
```css
.first {
    /* this is flex */
    display: flex;
}

.second {
    margin: auto;
    display: flex;
}
```
gets formatted to the incorrect:
```css
.first {
    /* this is flex */
    display: flex;
}

.second {
    /* this is flex */
    display: flex;

    margin: auto;
}
```
