### ISSUE TITLE
[CSS Orderer] Comments are broken when attached to variables

### ISSUE THREAD

**Issue by chocolateimage** [chocolateimage/chocotools#6]
Source:

```css
.test {
    /* Hello */
    --test: red;
}
```

Gives this bad output (comments disappear):

```css
.test {
    --test: red;
}
```

Comments should remain
